Recipe 5 add infrasructure layer
Far4ich/CullinaryBook pull request #3
Opened 2022-08-13 12:08 UTC by Far4ich

2022-08-13 19:58 UTC, Anatoliyphp reviewed
Этот ПР пока рано выкладывать, доменный слой еще не слит. Кроме этого нужно будет почитать про маппинги доменных моделей к базе данных, про подход Code First, который мы будем использовать. Сейчас все твои мапперы как минимум неполные + не отображены связи между сущностями.

2022-08-13 20:00 UTC, Anatoliyphp commented
https://metanit.com/sharp/entityframework/1.2.php - попробуй тут поизучать

2022-08-18 13:40 UTC, Anatoliyphp commented
А ты проект собирал вообще?

2022-08-18 13:46 UTC, Anatoliyphp commented on Infrastructure/Data/RecipeModel/EntityConfigurations/RecipeMap.cs
> +            builder.HasMany(x => x.Tag)
Сразу предупрежу такое не прокатит в EF Core

2022-08-18 13:47 UTC, Anatoliyphp commented on Infrastructure/Data/RecipeModel/EntityConfigurations/RecipeMap.cs
> +            builder.HasMany(x => x.Tag)
Имеется ввиду связь много-ко-многим

2022-08-18 15:53 UTC, Far4ich commented on Infrastructure/Data/RecipeModel/EntityConfigurations/RecipeMap.cs
> +            builder.HasMany(x => x.Tag)
я там сделал у тегов связь много-ко-многим вы про неё?

2022-08-19 09:21 UTC, Far4ich commented
Логика у лайков с избранным и тегов разная и чтобы сделать как с тегами мне бы пришлось добавлять дополнительные свойства List<Recipe> LikeRecipe в User и подобное для избранного, поэтому попробовал сделать как вы и написали связи внутри сущностей Like и Favorite

2022-08-19 09:29 UTC, sergoio0704 commented on Domain/Recipe/IRecipeRepository.cs
> +        List<RecipeTopDto> GetByTag(int id);
Давай называть не просто id, а указывать еще и сущность, например recipeId, tagId и т.д, чтобы сходу было понятно id какой сущности передается в метод

2022-08-19 09:30 UTC, sergoio0704 commented on Domain/Recipe/IRecipeRepository.cs
> +        RecipeTopDto GetBestRecipe();
Репозиторий должен по прежнему вернуть Recipe, в доменном слое никаких Dto быть не должно, вся конвертация должна происходить в слое Api, следовательно Dto должны лежать там же

2022-08-19 09:37 UTC, sergoio0704 commented on Domain/Recipe/IRecipeRepository.cs
> +        void SetTags(List<Tag> tags, int id);//планирую там же проверять существует ли тэг и создавать если его нет
Думаю, что от этого метода можно избавиться вообще. В отличие от лайков и избранных, теги можно добавить и привязать к рецепту лишь в момент создания/редактирования. В любом случае эта операция подразумевает возможность изменения всего рецепта -> как-то отдельно создавать теги мы не можем

2022-08-19 09:44 UTC, sergoio0704 commented on Domain/User/IUserRepository.cs
> +        void UpdateAboutMe(User user);
Лучше оставить Update как и было, мы же можем обновить не только описание, но и имя и т д.

2022-08-19 09:45 UTC, sergoio0704 commented on Infrastructure/Data/CullinaryBookContext.cs
> +        public DbSet<RecipeTag> RecipeId { get; set; }
Как будто бы не так должно называться)

2022-08-19 11:33 UTC, sergoio0704 commented on Infrastructure/Data/UserModel/UserRepository.cs
> +        public void UpdateAboutMe(User user)
Когда в IUserRepository откатили этот метод к названию Update, тут должна сейчас ошибка быть, надо поправить

2022-08-19 17:43 UTC, Anatoliyphp requested changes

2022-08-19 17:43 UTC, Anatoliyphp commented on Domain/Recipe/Recipe.cs
> +        public List<Tag> Tag { get; private set; } = new();
Поля, которые представляют собой списки писать во множественном числе(Tags и тд)

2022-08-19 17:43 UTC, Anatoliyphp commented on Domain/Tag/Tag.cs
> +        public List<Recipe> Recipe { get; set; } = new();
Убрать, оставить только связную сущность

2022-08-19 17:43 UTC, Anatoliyphp commented on Domain/Recipe/Recipe.cs
> +        public List<Tag> Tag { get; private set; } = new();
Из рецепта убрать Tag, оставить только смежную сущность

2022-08-19 17:43 UTC, Anatoliyphp commented on Domain/Recipe/Recipe.cs
> +        public List<Tag> Tag { get; private set; } = new();
Даже не так, тут нужно что-то одно выбрать, либо оставить Tag(придется инфрастуктуру править), но убрать RecipeTag(про такой вариант я и говорил, что ef может сломаться), либо оставить RecipeTag и убрать Tag(тут тоже может сломатся)
Предлагаю это пока оставить, потом уже при создании миграций посмотрим тоже

2022-08-19 17:43 UTC, Anatoliyphp commented on Infrastructure/Data/CullinaryBookContext.cs
> +        public async Task<bool> SaveEntitiesAsync(CancellationToken cancellationToken = default)
Этот метод здесь не нужен, за сохраненение отвечает UoW

2022-08-19 17:43 UTC, Anatoliyphp commented on Infrastructure/Data/IngredientModel/EntityConfigurations/IngredientMap.cs
> +            builder.Property(x => x.RecipeId);
Опять же просмотрим при запуске миграций, но лучше указывать в мелких сущностях связи с большими(рецепт-ингридиент)

2022-08-19 17:43 UTC, Anatoliyphp commented on Infrastructure/Data/StepModel/EntityConfigurations/StepMap.cs
> +            builder.HasKey(x => x.Id);
Все конфигурации нужно будет дополнить почитай про подход Code First и вот тут -https://docs.microsoft.com/ru-ru/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key

2022-08-19 17:43 UTC, Anatoliyphp commented on Infrastructure/UoW/UnitOfWork.cs
> +﻿using Infrastructure.Data;
Реализация UoW должна содержать в себе экземпляры репозиториев и динамически создавать их при необходимости(попробуй поискать в интернете информацию об этом)

2022-08-19 17:45 UTC, Anatoliyphp commented
После того, как апрувнем ПР не сливай его, создай первую миграцию и проверь, что все норм. Если нет будешь дорабатывать, такое своеобразное тестирование будет.

2022-08-22 11:05 UTC, Far4ich commented on Infrastructure/UoW/UnitOfWork.cs
> +﻿using Infrastructure.Data;
Сделал

2022-08-22 11:05 UTC, Far4ich commented on Infrastructure/Data/StepModel/EntityConfigurations/StepMap.cs
> +            builder.HasKey(x => x.Id);
Эту страничку я прочел и почитал про CodeFirst и единственное до чего я додумался это добавить ToTable() и внешние ключи вы про них?(пока не реализовал)

2022-08-22 11:05 UTC, Far4ich commented on Infrastructure/Data/IngredientModel/EntityConfigurations/IngredientMap.cs
> +            builder.Property(x => x.RecipeId);
Поправил

2022-08-22 11:05 UTC, Far4ich commented on Infrastructure/Data/CullinaryBookContext.cs
> +        public async Task<bool> SaveEntitiesAsync(CancellationToken cancellationToken = default)
Переделал

2022-08-22 11:05 UTC, Far4ich commented on Domain/Tag/Tag.cs
> +        public List<Recipe> Recipe { get; set; } = new();
если её удалить то ругается на связь многие ко многим в RecipeMap вот тут 
builder.HasMany(x => x.Tag)
             .WithMany(y => y.Recipe)
Думаю здесь пока оставить как есть как и в комментарии выше

2022-08-22 11:05 UTC, Far4ich commented on Domain/Recipe/Recipe.cs
> +        public List<Tag> Tag { get; private set; } = new();
Списки переименовал

2022-08-22 11:33 UTC, Anatoliyphp commented on Infrastructure/Data/StepModel/EntityConfigurations/StepMap.cs
> +            builder.HasKey(x => x.Id);
Поскольку мы в кода определяем какие у нас будут сущности и поля в базе, то нужно определять и их свойства также как при создании таблиц через sql. Как минимум null/not null max length, генерация id(HiLo, autoincrement и тд)

2022-08-22 22:11 UTC, sergoio0704 approved these changes

2022-08-23 09:14 UTC, Far4ich commented on Infrastructure/Data/StepModel/EntityConfigurations/StepMap.cs
> +            builder.HasKey(x => x.Id);
Поправил, почитал там можно еще тип сразу прописать, но этот метод есть только при написании свойства в контексте

2022-08-23 09:37 UTC, Anatoliyphp requested changes

2022-08-23 09:37 UTC, Anatoliyphp commented on Infrastructure/Data/IngredientModel/EntityConfigurations/IngredientMap.cs
> +            builder.Property(x => x.Id).ValueGeneratedOnAdd();
У тебя так id не определится как первичный ключ нужно оставить то что есть и добавить builder.HasKey обратно

2022-08-23 09:37 UTC, Anatoliyphp commented on Infrastructure/Data/IngredientModel/EntityConfigurations/IngredientMap.cs
>                  .WithMany(y => y.Ingredients);
Нигде не указаны внешние ключи для связей

2022-08-23 09:39 UTC, Anatoliyphp commented on Infrastructure/Data/CullinaryBookContext.cs
> +            base.OnModelCreating(builder);
Ни одна конфигурация не добавлена

2022-08-23 09:58 UTC, Far4ich commented on Infrastructure/Data/CullinaryBookContext.cs
> +            base.OnModelCreating(builder);
builder.ApplyConfigurationsFromAssembly(Assembly.GetExecutingAssembly()); - Применяет конфигурацию из всех IEntityTypeConfiguration<TEntity> экземпляров, определенных в предоставленной сборке.
https://docs.microsoft.com/ru-ru/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1?view=efcore-5.0

2022-08-23 10:00 UTC, Far4ich commented on Infrastructure/Data/IngredientModel/EntityConfigurations/IngredientMap.cs
>                  .WithMany(y => y.Ingredients);
Поправил

2022-08-23 10:02 UTC, Far4ich commented on Infrastructure/Data/IngredientModel/EntityConfigurations/IngredientMap.cs
> +            builder.Property(x => x.Id).ValueGeneratedOnAdd();
Вернул, я просто прочел информацию что EF сам ключ выставляет если в имени Id(хотя это наверное не практично)

2022-08-23 10:28 UTC, Anatoliyphp commented on Infrastructure/Data/CullinaryBookContext.cs
> +            base.OnModelCreating(builder);
Это конечно вещь крутая, но только тогда, когда не важен порядок конфигурируемых сущностей(она их рандомно будет устанавливать). Поэтому когда у тебя будет создаваться миграция, может быть ситуация когда ингредиент создастся до рецепта и выкинет ошибку, так как он является связной сущностью, с внешним ключем к таблице которой еще нет.

2022-08-23 10:29 UTC, Anatoliyphp commented on Infrastructure/Data/CullinaryBookContext.cs
> +            base.OnModelCreating(builder);
Поэтому лучше явно эти вещи прописывать в нужном порядке

2022-08-23 10:32 UTC, Anatoliyphp commented on Infrastructure/Data/UserModel/EntityConfigurations/UserMap.cs
> +            builder.HasMany(x => x.Recipes)
Эту связь лучше в рецепте прописать, в базе у тебя таблица пользователя не будет содержать информации о том, что у него много рецептов, наоборот рецепт будет эту связь содержать в виде внешнего ключа.

2022-08-23 10:33 UTC, Anatoliyphp commented on Infrastructure/Data/UserModel/EntityConfigurations/UserMap.cs
> +            builder.HasMany(x => x.Recipes)
Посмотри еще по коду, есть ли похожие случаи

2022-08-24 10:00 UTC, Far4ich commented on Infrastructure/Data/UserModel/EntityConfigurations/UserMap.cs
> +            builder.HasMany(x => x.Recipes)
Поправил, похожих не нашел

2022-08-24 10:00 UTC, Far4ich commented on Infrastructure/Data/CullinaryBookContext.cs
> +            base.OnModelCreating(builder);
Учту, поправил

2022-08-24 17:52 UTC, sergoio0704 commented on Infrastructure/Infrastructure.csproj
> +    <ProjectReference Include="..\Api\Api.csproj" />
Ссылка на проект Api не нужна в слое Infrastructure

2022-08-25 12:37 UTC, Anatoliyphp reviewed
В целом вроде бы норм, перепроверь свою базу(может название не-то или подключение не правильное)

2022-08-25 12:37 UTC, Anatoliyphp commented on Domain/Ingredient/Ingredient.cs
>      public class Ingredient
Не понятно, зачем импортнул Abp, если не используешь Entity(от него нужно унаследоваться), плюс айдишники оставил как были(если использовать Entity их вообще не нужно указывать). Давай что-то одно выберем: либо используешь Entity и не указываешь Id, либо не используешься Entity, не импортишь abp, прописываешь Id

2022-08-25 12:37 UTC, Anatoliyphp commented on Domain/Recipe/Recipe.cs
> +        public Recipe(int id, string title, string description, int cookingMinutes, int numberOfServings, string image, int authorId)
Для удобочитаемости(если аргументов больше 2) записывай аргументы конструктора с новой строки:
public Recipe(
    int id;
    string title;
)

2022-08-25 12:37 UTC, Anatoliyphp commented on Infrastructure/Data/CullinaryBookContext.cs
> +           //builder.ApplyConfiguration(new RecipeTagMap());
Что это?

2022-08-25 16:07 UTC, Far4ich commented on Domain/Ingredient/Ingredient.cs
>      public class Ingredient
Я сначала его использовал, но у меня появился косяк при миграции он находил Property внутри Entity и просил для него указать ключ. Оставлю Id скорее всего, решения не нашел как это поправить.
Запушил второпях - нужно было идти, поэтому очень грязно в коде.

2022-08-25 16:07 UTC, Far4ich commented on Domain/Recipe/Recipe.cs
> +        public Recipe(int id, string title, string description, int cookingMinutes, int numberOfServings, string image, int authorId)
Учту, завтра поправлю

2022-08-25 16:08 UTC, Far4ich commented on Infrastructure/Data/CullinaryBookContext.cs
> +           //builder.ApplyConfiguration(new RecipeTagMap());
Уберу, это я боролся с Property в Entity своими силами думал проблема в связи.

2022-08-29 09:06 UTC, Anatoliyphp approved these changes

2022-08-30 08:34 UTC, merged