implemented a repository, add dto, add controller
Far4ich/CullinaryBook pull request #4
Opened 2022-08-30 12:10 UTC by Far4ich

2022-08-31 10:16 UTC, Anatoliyphp requested changes

2022-08-31 10:16 UTC, Anatoliyphp commented on Api/Dto/RecipeTopDto.cs
> +        public RecipeTopDto(
Давай для DTO будем использовать record

2022-08-31 10:16 UTC, Anatoliyphp commented on Infrastructure/Data/RecipeModel/RecipeRepository.cs
> +            _dbContext.Favorite.Add(new Favorite(0, userId, recipeId));
Что за 0?

2022-08-31 10:16 UTC, Anatoliyphp commented on Infrastructure/Data/RecipeModel/RecipeRepository.cs
> +            _dbContext.Like.Add(new Like(0, userId, recipeId));
Что за 0?

2022-08-31 10:16 UTC, Anatoliyphp commented on Infrastructure/Data/RecipeModel/RecipeRepository.cs
> +            return _dbContext.Recipe.SingleOrDefault(recipe => recipe.Id == recipeId);
Тут нужно будет либо несколько методов для получения полного рецепта( с ингредиентами и тд) и не полного, либо добавить динамический includemultiple(нужно погуглить)

2022-08-31 10:16 UTC, Anatoliyphp commented on Infrastructure/Data/RecipeModel/RecipeRepository.cs
> +            _dbContext.Recipe.Remove(Get(recipeId));
Давай все-таки будем разделять операции внутри методов, для лучшей читаемости. (остальные тоже)

2022-08-31 10:16 UTC, Anatoliyphp commented on Infrastructure/Data/RecipeModel/RecipeRepository.cs
> +            return _dbContext.Recipe.SingleOrDefault(recipe => recipe.Id == recipeId);
+ Все методы переделать на асинхронные

2022-08-31 10:16 UTC, Anatoliyphp commented on Infrastructure/Data/RecipeModel/RecipeRepository.cs
> +            return (List<Recipe>)_dbContext.Recipe.Where(recipe => recipe.Tags.Find(t => t.Id == tagId) != null);
Этот метод нужно пересмотреть. Я бы предложил сделать универсальный метод, который принимает список id тэгов, и возвращает все рецепты, у которых есть хотя бы один такой тэг.

2022-08-31 10:16 UTC, Anatoliyphp commented on Infrastructure/Data/RecipeModel/RecipeRepository.cs
> +            _dbContext.Recipe.Add(recipe);
Ты добавил DTO и метод для лучшего рецепта, а нужно было для полного рецепта(именно создание)

2022-08-31 10:16 UTC, Anatoliyphp commented on Infrastructure/Data/RecipeModel/RecipeRepository.cs
> +            _dbContext.Recipe.Remove(Get(recipeId));
Или выделить сервис под это дело, чтобы каждый метод репозитория выполнял конкретную базовую операцию, а сервис уже будет ими манипулировать для более сложных операций.

2022-08-31 18:47 UTC, Anatoliyphp commented on Infrastructure/Data/RecipeModel/RecipeRepository.cs
> +            return (List<Recipe>)_dbContext.Recipe.Where(recipe => recipe.Tags.Find(t => t.Id == tagId) != null);
Есть еще вариант использовать join метод ef core. Но тут нужно будет подумать над самим запросом и попробовать сначала составить его в sql.
https://metanit.com/sharp/entityframeworkcore/5.3.php

2022-09-02 17:54 UTC, Anatoliyphp requested changes

2022-09-02 17:54 UTC, Anatoliyphp commented on Api/Dto/RecipeBestDto.cs
> +        public RecipeBestDto(
Почитай как правильно оформлять record. Плюс у dto не должно быть конструктора

2022-09-02 17:54 UTC, Anatoliyphp commented on Api/Dto/RecipeFullDto.cs
> +        public List<Tag> Tags { get; private set; }
Для все вложенных сущностей нужны свои dto, сейчас у тебя тэги, шаги, лайки, избранное - все доменные сущности

2022-09-02 17:54 UTC, Anatoliyphp commented on Api/Dto/RecipeFullDto.cs
> +    public record RecipeFullDto
Название просто RecipeDto

2022-09-02 17:54 UTC, Anatoliyphp commented on Api/Dto/RecipeListDto.cs
> +        public RecipeListDto(
Подумай над названием, сейчас оно говорит о том, что это dto списка рецептов.

2022-09-02 17:54 UTC, Anatoliyphp commented on Api/Program.cs
> +builder.Services.AddScoped<IUnitOfWork, UnitOfWork>();
Вынести в extension, как выносил получение бд контекста. Для каждого проекта сделай свой extension, и туда добавляй зависимости(относящиеся к этому проекту)

2022-09-02 17:54 UTC, Anatoliyphp commented on Api/Services/IRecipeService.cs
> +        List<RecipeListDto> GetAll();
Сделать асинхронным

2022-09-02 17:54 UTC, Anatoliyphp commented on Api/Services/Mappers/RecipeMapper.cs
> +        public static RecipeBestDto MapToRecipeBestDto(this Recipe recipe)
Переделай в билдер, так как с появлением вложенных сущностей появится бОльшая логика. Для самих вложенных сущностей можешь сделать мапперы.

2022-09-02 17:54 UTC, Anatoliyphp commented on Api/Services/RecipeService.cs
> +                throw new Exception($"{nameof(Recipe)} not found");
в исключении подставляешь в nameof доменную сущность, переделай на dto

2022-09-02 17:54 UTC, Anatoliyphp commented on Api/Services/RecipeService.cs
> +                throw new Exception($"{nameof(Recipe)} not found");
Добавь еще сразу валидацию dto(во всех методах), проверяй все возможные случаи, которые могут привести к ошибке. Можешь использовать атрибуты, можешь использовать паттерн валидатор на твой выбор.

2022-09-02 17:54 UTC, Anatoliyphp commented on Infrastructure/Data/RecipeModel/RecipeRepository.cs
> +                .Include(x=>x.Likes)
Забыл тэги и избранное. Лайки и избранное тебе не будут нужны как сущности, тебе нужно только их количество, подумай как это получить и где(в сервисе или репозитории)

2022-09-02 17:54 UTC, Anatoliyphp commented on Infrastructure/Services/RecipeRepositoryService.cs
> +    {
Что это?

2022-09-06 17:49 UTC, Anatoliyphp commented on Api/Dto/FavoriteDto.cs
> +    {
record не нуждается в теле убери скобки. Тело объявляется редко, если есть необходисмость

2022-09-06 17:49 UTC, Anatoliyphp commented on Api/Dto/LikeDto.cs
> +        int Id,
Уверен что в DTO лайков избранных и тэгов нам понадобятся их id?

2022-09-06 17:49 UTC, Anatoliyphp commented on Api/Services/Builders/RecipeBuilder.cs
> +        public RecipeBuilder BuildIngredients(RecipeEditDto recipeDto)
Уверен что эти методы будут использоваться вне билдера? Помоему логично сделать их приватными и уже в методах по сборке полного рецепта использовать

2022-09-06 17:49 UTC, Anatoliyphp commented on Infrastructure/Data/RecipeModel/RecipeRepository.cs
> +                .Include(recipe => recipe.Author)
Зачем здесь автор рецепта?

2022-09-06 17:49 UTC, Anatoliyphp commented on Infrastructure/Data/RecipeModel/RecipeRepository.cs
> +                .Include(recipe => recipe.Author)
И во стальных метсах

2022-09-06 18:57 UTC, Far4ich commented on Infrastructure/Data/RecipeModel/RecipeRepository.cs
> +                .Include(recipe => recipe.Author)
Поправил, не помню зачем там его добавил

2022-09-06 18:57 UTC, Far4ich commented on Api/Services/Builders/RecipeBuilder.cs
> +        public RecipeBuilder BuildIngredients(RecipeEditDto recipeDto)
Ну предполагалось сделать универсальный билдер, но здесь все равно требуются все методы так что и вправду логичнее их закинуть в сборку рецепта(закинул)

2022-09-06 18:57 UTC, Far4ich commented on Api/Dto/LikeDto.cs
> +        int Id,
Не нужны, поправил

2022-09-06 18:57 UTC, Far4ich commented on Api/Dto/FavoriteDto.cs
> +    {
Поправил

2022-09-08 16:30 UTC, sergoio0704 commented on Api/Controllers/RecipeController.cs
> +        public async Task<IActionResult> GetRecipeList()
GetRecipeList -> GetRecipes

2022-09-08 16:31 UTC, sergoio0704 commented on Api/Controllers/RecipeController.cs
> +        public async Task<IActionResult> CreateRecipe([FromBody]RecipeEditDto recipe)
`[FromBody]RecipeEditDto recipe` -> `[FromBody] RecipeEditDto recipe` форматирование

2022-09-08 16:32 UTC, sergoio0704 commented on Api/Controllers/RecipeController.cs
> +        public async Task<IActionResult> DeleteRecipes(int recipeId)
`DeleteRecipes` -> `DeleteRecipe`

2022-09-08 16:32 UTC, sergoio0704 commented on Api/Controllers/RecipeController.cs
> +        public async Task<IActionResult> UpdateRecipes([FromBody] RecipeEditDto recipe)
`UpdateRecipes` -> `UpdateRecipe`

2022-09-08 16:39 UTC, sergoio0704 commented on Api/Services/RecipeService.cs
> +            List<Tag> tags = await _recipeRepository.GetAllTags();
Давай тэги будем получать в методе BuildTags

2022-09-08 16:46 UTC, sergoio0704 commented on Api/Services/Builders/IRecipeBuilder.cs
> +        RecipeBuilder BuildRecipeData(RecipeEditDto recipeDto, List<Tag> tags);
Давай избавимся от методов BuildNewRecipe и BuildRecipeForUpdate, оставим просто метод Build

2022-09-08 16:48 UTC, sergoio0704 commented on Infrastructure/Data/RecipeModel/RecipeRepository.cs
> +        //перекинуть в сервис добавить проверку на null
Надо доделать)

2022-09-08 16:48 UTC, sergoio0704 commented on Infrastructure/Data/RecipeModel/RecipeRepository.cs
> +            var recipe = await _dbContext.Recipe
можно сразу retun await как сделал в методе ниже

2022-09-08 16:49 UTC, sergoio0704 commented on Infrastructure/Data/RecipeModel/RecipeRepository.cs
> +        public async Task<List<Recipe>> GetRecipeList()
GetRecipes*

2022-09-08 16:49 UTC, sergoio0704 commented on Infrastructure/Data/RecipeModel/RecipeRepository.cs
> +        public async Task<List<Tag>> GetAllTags()
GetTags

2022-09-08 16:49 UTC, sergoio0704 commented on Infrastructure/Data/RecipeModel/RecipeRepository.cs
> +        //перекинуть в сервис, добавить проверку на null
Надо доделать

2022-09-08 16:50 UTC, sergoio0704 commented on Infrastructure/Data/RecipeModel/RecipeRepository.cs
> +        //перекинуть в сервис, добавить проверку на null
!

2022-09-08 16:52 UTC, sergoio0704 commented on Infrastructure/Data/RecipeModel/RecipeRepository.cs
> +        public async Task SetFavorite(int recipeId, int userId)
Давай сделаем, чтобы методы Remove/Set Like и Remove/Set Favorite сразу принимали в параметрах метода нужные сущности, а не создавались внутри метода.

public async Task SetFavorite(Favorite favorite)...

А создавать объект будем на уровне сервиса

2022-09-08 16:54 UTC, sergoio0704 commented on Domain/Recipe/RecipeTag.cs
> +        public RecipeTag() { }
Давай все конструкторы удалим, так как они не используются

2022-09-08 17:00 UTC, sergoio0704 commented on Api/Services/Mappers/TagMapper.cs
> +            return new TagDto(
Для чего тут перенос? return new Tag(tag.Title); в одну строку, тоже самое и в методе ниже

2022-09-08 17:02 UTC, sergoio0704 commented on Api/Services/Mappers/LikeMapper.cs
> +            return new LikeDto(
Тут тоже самое как и в тегах, перенос обычно делается, когда больше 3-х параметров, исключение, если у параметров длинные названия, и в область редактора IDE не помещается строка кода

2022-09-08 17:02 UTC, sergoio0704 commented on Api/Services/Mappers/FavoriteMapper.cs
> +            return new FavoriteDto(
Убрать перенос параметров

2022-09-08 17:07 UTC, sergoio0704 commented on Api/Dto/RecipeEditDto.cs
> +        List<TagDto> TagDtos,
В названиях полей не нужно писать приставку Dto/Dtos

2022-09-08 17:09 UTC, sergoio0704 commented on Api/Services/RecipeService.cs
> +            List<Tag> tags = await _recipeRepository.GetAllTags();
Еще нужно сделать инициализацию ленивой, почитай про Lazy
Это нужно для того, чтобы каждый раз при инициализации конструктора билдера не дергались тэги из базы

Попробуй реализовать это, если не получится, то потом созвонимся, обсудим

2022-09-09 08:54 UTC, Far4ich commented on Api/Dto/RecipeEditDto.cs
> +        List<TagDto> TagDtos,
Поправил, учту

2022-09-09 08:54 UTC, Far4ich commented on Api/Services/Mappers/FavoriteMapper.cs
> +            return new FavoriteDto(
Поправил

2022-09-09 08:54 UTC, Far4ich commented on Api/Services/Mappers/LikeMapper.cs
> +            return new LikeDto(
Поправил, учту, писал на автомате уже и не заметил(Анатолий подобные вещи говорил)

2022-09-09 08:54 UTC, Far4ich commented on Api/Services/Mappers/TagMapper.cs
> +            return new TagDto(
Поправил

2022-09-09 08:54 UTC, Far4ich commented on Domain/Recipe/RecipeTag.cs
> +        public RecipeTag() { }
Вы ведь про все конструкторы именно в этом классе(удалил), у остальных используются в мапперах(не трогал)

2022-09-09 08:54 UTC, Far4ich commented on Infrastructure/Data/RecipeModel/RecipeRepository.cs
> +        public async Task SetFavorite(int recipeId, int userId)
Переделал

2022-09-09 08:54 UTC, Far4ich commented on Infrastructure/Data/RecipeModel/RecipeRepository.cs
> +        //перекинуть в сервис, добавить проверку на null
Убрал

2022-09-09 08:54 UTC, Far4ich commented on Infrastructure/Data/RecipeModel/RecipeRepository.cs
> +        //перекинуть в сервис, добавить проверку на null
Доделал

2022-09-09 08:54 UTC, Far4ich commented on Infrastructure/Data/RecipeModel/RecipeRepository.cs
> +        public async Task<List<Tag>> GetAllTags()
Поправил

2022-09-09 08:54 UTC, Far4ich commented on Infrastructure/Data/RecipeModel/RecipeRepository.cs
> +        public async Task<List<Recipe>> GetRecipeList()
Поправил

2022-09-09 08:54 UTC, Far4ich commented on Infrastructure/Data/RecipeModel/RecipeRepository.cs
> +            var recipe = await _dbContext.Recipe
Он там мог null вернуть, перенес в сервис

2022-09-09 08:54 UTC, Far4ich commented on Infrastructure/Data/RecipeModel/RecipeRepository.cs
> +        //перекинуть в сервис добавить проверку на null
Доделал

2022-09-09 08:54 UTC, Far4ich commented on Api/Services/Builders/IRecipeBuilder.cs
> +        RecipeBuilder BuildRecipeData(RecipeEditDto recipeDto, List<Tag> tags);
Поправил, если я правильно понял то нужно сделать перегрузку Build так как для update нужно иметь ссылку на объект полученный из базы

2022-09-09 08:54 UTC, Far4ich commented on Api/Services/RecipeService.cs
> +            List<Tag> tags = await _recipeRepository.GetAllTags();
Поправил

2022-09-09 08:54 UTC, Far4ich commented on Api/Controllers/RecipeController.cs
> +        public async Task<IActionResult> UpdateRecipes([FromBody] RecipeEditDto recipe)
Поправил

2022-09-09 08:54 UTC, Far4ich commented on Api/Controllers/RecipeController.cs
> +        public async Task<IActionResult> DeleteRecipes(int recipeId)
Поправил

2022-09-09 08:54 UTC, Far4ich commented on Api/Controllers/RecipeController.cs
> +        public async Task<IActionResult> CreateRecipe([FromBody]RecipeEditDto recipe)
Поправил

2022-09-09 08:54 UTC, Far4ich commented on Api/Controllers/RecipeController.cs
> +        public async Task<IActionResult> GetRecipeList()
Поправил

2022-09-12 10:31 UTC, Anatoliyphp approved these changes

2022-09-12 10:31 UTC, Anatoliyphp commented on Api/Services/Builders/IRecipeBuilder.cs
> +        Task<RecipeBuilder> BuildAll(RecipeEditDto recipeDto);
Кого всех?

2022-09-12 17:21 UTC, sergoio0704 approved these changes

2022-09-13 13:07 UTC, merged