Recipe 7 add site create recipe
Far4ich/CullinaryBook pull request #5
Opened 2022-09-21 16:23 UTC by Far4ich

2022-09-21 18:39 UTC, sergoio0704 commented on Api/Controllers/UserController.cs
> +        [Route("get-likes/{userId}")]
Давай из Route уберем слово get и поменяем немного название
Предлагаю что-то в духе "{userId}/likes", чтобы полный путь выглядел "http://localhost/user/3/likes"

2022-09-21 18:42 UTC, sergoio0704 commented on Api/Services/RecipeService.cs
>              _recipeRepository.RemoveFavorite(favorite);
Давай операции удаления в репозитории тоже сделаем асинхронными

2022-09-21 18:45 UTC, sergoio0704 commented on CullinaryBookSite/ClientApp/src/app/Modules/CreateRecipePage/Components/page/create-recipe-page.component.ts
> +
Лишний перенос строки

2022-09-21 19:34 UTC, Anatoliyphp requested changes

2022-09-21 19:34 UTC, Anatoliyphp commented on Api/Services/UserService.cs
> +            return favorites.ConvertAll(l => l.MapToFavoriteDto());
Почему l?

2022-09-21 19:34 UTC, Anatoliyphp commented on CullinaryBookSite/ClientApp/src/app/Services/recipe.service.ts
> +    private readonly apiUrl: string = 'http://localhost:4200/api/recipe';
Давай вынесем апишку в конфиг файл

2022-09-21 19:34 UTC, Anatoliyphp commented on CullinaryBookSite/ClientApp/src/app/Modules/RecipesPage/recipes-page-routing.module.ts
> +const routes: Routes = [
Все маршруты вынести в app.routing.module

2022-09-21 19:34 UTC, Anatoliyphp commented on CullinaryBookSite/ClientApp/src/app/Dto/recipeDto.ts
> +    id?: number;
В каком случае тут может быть undefined? Посмотри в других местах тоже поправь

2022-09-21 19:34 UTC, Anatoliyphp commented on CullinaryBookSite/ClientApp/src/app/Modules/MainPage/Components/recipe-search/recipe-search.component.html
> +            <span class="recipe-search-form-tags-item">Мясо</span>
Вынести в отедельный компонент

2022-09-21 19:34 UTC, Anatoliyphp commented on CullinaryBookSite/ClientApp/src/app/Modules/CreateRecipePage/Components/page/create-recipe-page.component.ts
> +    publicClicked(): void
Название ни о чем не говорит

2022-09-21 19:34 UTC, Anatoliyphp commented on CullinaryBookSite/ClientApp/src/app/Modules/CreateRecipePage/Components/page/create-recipe-page.component.html
> +            <img class="add-recipe-top-img" src="../../../../../assets/images/img-input.svg">
Нужно добавить валидацию полей создания рецепта

2022-09-21 19:34 UTC, Anatoliyphp commented on CullinaryBookSite/ClientApp/src/app/Modules/RecipesPage/Components/page/recipes-page.component.html
> +            [favorited]="isFavorited(recipe.id)"
IsFavorite - favorite

2022-09-21 19:34 UTC, Anatoliyphp commented on CullinaryBookSite/ClientApp/src/app/Modules/RecipesPage/Components/page/recipes-page.component.ts
> +        this.refreshRecipes();
Это нужно вынести в ngOnInit - почитай

2022-09-21 19:34 UTC, Anatoliyphp commented on CullinaryBookSite/ClientApp/src/app/Modules/RecipesPage/Components/recipe-search/recipe-search.component.html
> +<div class="recipe-search-form">
Зачем еще один search?

2022-09-22 16:17 UTC, Far4ich commented on CullinaryBookSite/ClientApp/src/app/Modules/RecipesPage/Components/page/recipes-page.component.html
> +            [favorited]="isFavorited(recipe.id)"
Не понял в чем проблема. Нужно переименовать методы?

2022-09-22 17:01 UTC, Far4ich commented on Api/Controllers/UserController.cs
> +        [Route("get-likes/{userId}")]
Поправил, у избранных так же переделал

2022-09-22 17:01 UTC, Far4ich commented on Api/Services/RecipeService.cs
>              _recipeRepository.RemoveFavorite(favorite);
это не имеет смысла так как EF при Remove просто помечает объект для удаления само удаление происходит при сохранении(рецепты удаляются точно также)

2022-09-22 17:01 UTC, Far4ich commented on CullinaryBookSite/ClientApp/src/app/Modules/CreateRecipePage/Components/page/create-recipe-page.component.ts
> +
Поправил

2022-09-22 17:01 UTC, Far4ich commented on Api/Services/UserService.cs
> +            return favorites.ConvertAll(l => l.MapToFavoriteDto());
Поправил, не заметил

2022-09-22 17:01 UTC, Far4ich commented on CullinaryBookSite/ClientApp/src/app/Services/recipe.service.ts
> +    private readonly apiUrl: string = 'http://localhost:4200/api/recipe';
Вынес

2022-09-22 17:01 UTC, Far4ich commented on CullinaryBookSite/ClientApp/src/app/Modules/RecipesPage/recipes-page-routing.module.ts
> +const routes: Routes = [
Поправил

2022-09-22 17:01 UTC, Far4ich commented on CullinaryBookSite/ClientApp/src/app/Dto/recipeDto.ts
> +    id?: number;
Поправил, еще убрал у лучшего рецепта

2022-09-22 17:01 UTC, Far4ich commented on CullinaryBookSite/ClientApp/src/app/Modules/MainPage/Components/recipe-search/recipe-search.component.html
> +            <span class="recipe-search-form-tags-item">Мясо</span>
Вынес

2022-09-22 17:01 UTC, Far4ich commented on CullinaryBookSite/ClientApp/src/app/Modules/CreateRecipePage/Components/page/create-recipe-page.component.ts
> +    publicClicked(): void
Переименовал

2022-09-22 17:01 UTC, Far4ich commented on CullinaryBookSite/ClientApp/src/app/Modules/RecipesPage/Components/page/recipes-page.component.ts
> +        this.refreshRecipes();
Вынес, почитал

2022-09-22 17:01 UTC, Far4ich commented on CullinaryBookSite/ClientApp/src/app/Modules/RecipesPage/Components/recipe-search/recipe-search.component.html
> +<div class="recipe-search-form">
Убрал

2022-09-23 09:34 UTC, Far4ich commented on CullinaryBookSite/ClientApp/src/app/Modules/CreateRecipePage/Components/page/create-recipe-page.component.html
> +            <img class="add-recipe-top-img" src="../../../../../assets/images/img-input.svg">
Добавил, но пока без валидации картинки

2022-09-26 17:57 UTC, sergoio0704 commented on CullinaryBookSite/ClientApp/src/app/Modules/CreateRecipePage/Components/page/create-recipe-page.component.ts
> +            this.recipe.image = e.target!.result?.toString()!;
Чтобы картинка отобразилась сразу при загрузке файла - можно оставить e.target!.result без toString()
На бэк - лучше передавать сам объект file

2022-09-26 18:01 UTC, Anatoliyphp requested changes

2022-09-26 18:01 UTC, Anatoliyphp commented on Api/Services/Builders/RecipeBuilder.cs
> +                _imageService.DeleteImage(_recipe.Image);
Что это?

2022-09-26 18:01 UTC, Anatoliyphp commented on Api/Services/ImageService.cs
> +        private readonly string _imagesPath = "C:\\Users\\Alex\\Desktop\\Practice\\SaveImages";
Давай вынесем в конфиг

2022-09-26 18:01 UTC, Anatoliyphp commented on CullinaryBookSite/ClientApp/src/app/Modules/CreateRecipePage/Components/page/create-recipe-page.component.ts
> +        if (this.recipe.title.length == 0)
Почитай про то, как реализуются валидаторы в Angular. Нужно переделать

2022-09-26 18:01 UTC, Anatoliyphp commented on CullinaryBookSite/ClientApp/src/app/Modules/RecipesPage/Components/page/recipes-page.component.ts
> +        if (like != undefined)
В чем логика? как like может быть undefined?

2022-09-26 18:01 UTC, Anatoliyphp commented on CullinaryBookSite/ClientApp/src/app/Modules/RecipesPage/Components/page/recipes-page.component.ts
> +        if (favorite != undefined)
Тоже самое

2022-09-26 18:01 UTC, Anatoliyphp commented on CullinaryBookSite/ClientApp/src/app/Modules/RecipesPage/Components/page/recipes-page.component.ts
> +        if (recipeId != undefined)
Как id рецепта может быть undefined?

2022-09-26 18:02 UTC, sergoio0704 commented on Api/Services/ImageService.cs
> +        private readonly string _imagesPath = "C:\\Users\\Alex\\Desktop\\Practice\\SaveImages";
Давай вынесем в конфиг

2022-09-26 18:04 UTC, sergoio0704 commented on Api/Services/ImageService.cs
> +        public async Task<string> SaveImage(string image)
Давай в дто при создании рецепта принимать не строку, а IFormFIle
https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.aspnetcore.http.iformfile.contenttype?view=aspnetcore-6.0
В нем должна быть уже вся нужная информация

2022-09-27 15:35 UTC, Far4ich commented on CullinaryBookSite/ClientApp/src/app/Modules/CreateRecipePage/Components/page/create-recipe-page.component.ts
> +            this.recipe.image = e.target!.result?.toString()!;
![image](https://user-images.githubusercontent.com/79937711/192570674-e8cd942f-1b3b-43d7-a573-fc8a988374c8.png)
Там тип ArrayBuffer еще

2022-09-27 15:50 UTC, Far4ich commented on CullinaryBookSite/ClientApp/src/app/Modules/RecipesPage/Components/page/recipes-page.component.ts
> +        if (like != undefined)
Суть в том что я сохраняю лайки/избранные в likes/favorites и в случае если пользователь убирает лайк/избранное он удаляется из likes/favorites и идет другая логика при не найденном лайке/избранном

2022-09-27 19:41 UTC, Far4ich commented on Api/Services/ImageService.cs
> +        public async Task<string> SaveImage(string image)
Поправил

2022-09-27 19:41 UTC, Far4ich commented on CullinaryBookSite/ClientApp/src/app/Modules/RecipesPage/Components/page/recipes-page.component.ts
> +        if (recipeId != undefined)
Поправил

2022-09-27 19:41 UTC, Far4ich commented on Api/Services/ImageService.cs
> +        private readonly string _imagesPath = "C:\\Users\\Alex\\Desktop\\Practice\\SaveImages";
Вынес

2022-09-27 19:41 UTC, Far4ich commented on Api/Services/Builders/RecipeBuilder.cs
> +                _imageService.DeleteImage(_recipe.Image);
Убрал, думал здесь сделать логику отчистки старого изображения(но это пока не нужно обновления нету)

2022-09-27 19:41 UTC, Far4ich commented on CullinaryBookSite/ClientApp/src/app/Modules/CreateRecipePage/Components/page/create-recipe-page.component.ts
> +            this.recipe.image = e.target!.result?.toString()!;
Поправил

2022-09-28 19:33 UTC, sergoio0704 approved these changes

2022-09-28 19:39 UTC, Anatoliyphp approved these changes

2022-09-29 06:07 UTC, merged